version: "3.8"
services:
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:2.0-openssl
    restart: always
    volumes: 
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data/
      - ./log:/mosquitto/log/
    ports:
      - 1883:1883
      - 9001:9001

  python-app:
    build:
      context: .
    restart: always
    depends_on:
      - mqtt